import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading } = api.user.getAll.useQuery();

  if (isLoading) return <div>Loading..</div>;

  if (!data || data.length === 0) return <div>No users.</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data?.map((user) => {
          return <div key={user?.id}>{user?.name}</div>;
        })}
      </main>
    </>
  );
}
